# Generated by Django 3.2.8 on 2022-01-24 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=200, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(default='', max_length=200)),
                ('security_question', models.CharField(default='', max_length=200)),
                ('security_answer', models.CharField(default='', max_length=200)),
                ('pin', models.CharField(default='', max_length=100)),
                ('token', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='0', max_length=100)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
