# Generated by Django 3.2.8 on 2022-01-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_myuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_superuser',
        ),
    ]
